{{- range $name, $config := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k3s-app.fullname" $ }}-{{ $name }}
  labels:
    {{- include "k3s-app.labels" $ | nindent 4 }}
data:
  {{- toYaml $config.data | nindent 2 }}
{{- end }}