{{- range $name, $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k3s-app.fullname" $ }}-{{ $name }}
  labels:
    {{- include "k3s-app.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}